# Generated by Django 2.2.3 on 2019-07-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_Comissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('month', models.IntegerField()),
                ('comission', models.FloatField()),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sellers')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
