# Generated by Django 2.2.3 on 2019-07-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_Comissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('comission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sellers')),
            ],
            options={
                'verbose_name': 'Comissão Mensal Vendedor',
                'verbose_name_plural': 'Comissões Mensal Vendedor',
            },
        ),
    ]
