# Generated by Django 2.2.3 on 2019-07-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_month_comissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_comissions',
            name='comission',
            field=models.FloatField(blank=True),
        ),
    ]
